version: "3"

services:
  app:
    build: ./docker
    container_name: ctf_container
    working_dir: /src
    tty: true
    volumes:
      - .:/src
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
